### ISSUE TITLE
Refactor the featured announcement section into a reusable React component that renders conditionally.

### ISSUE THREAD

**Issue by atasoya** [atasoya/emu-guide#2]
For the sake of code modularity and reusability, the featured announcement which is currently hard coded should be developed as a separate component. Such a component would render on the screen only under certain conditions and would render different texts based on the current language setting.

#### Task Details:
- Create a React component named ` FeaturedAnnouncement `.
- Ensure it accepts ` show ` and ` language ` as props.
- Render the announcement only if show is ` true `.
- Display English or Turkish text based on the language prop.
- Maintain the existing design and link behavior.

#### Acceptance Criteria:
- The new component renders correctly with conditional logic.
- The UI and styling remain consistent with the existing section.
- The component is tested for both show being ` true ` and ` false `.

**Comment by fcendesu** [comment]
I would like to do that
