### ISSUE TITLE
Refactor FeaturedAnnouncement Component to Accept HTML Input and Render English and Turkish Announcements Conditionally

### ISSUE THREAD

**Issue by atasoya** [atasoya/emu-guide#6]
**Description:**
The current `FeaturedAnnouncement` component is limited in its input capabilities and does not support HTML content or conditional rendering for different languages. To improve its functionality and make it adaptable for multilingual announcements, we need to refactor the component to meet the following requirements:

**Requirements:**
1. **HTML Content Support:**
   - Update the `FeaturedAnnouncement` component to accept HTML input so that formatted text, links, and embedded elements can be rendered correctly.

2. **Conditional Language Rendering:**
   - Add support to the component to render announcements in either English or Turkish based on a language prop.
   - Ensure that the language prop can be passed down to determine the content that should be displayed (e.g., `lang='en'` for English and `lang='tr'` for Turkish).

**Acceptance Criteria:**
- The `FeaturedAnnouncement` component must be able to parse and render valid HTML content securely.
- The component should have a prop (e.g., `lang`) that switches between English and Turkish announcements.
- The component must render the correct announcement content based on the provided `lang` prop.
- Ensure that the component properly handles cases where one of the language contents is not available (e.g., fallback logic or default message).
- Verify that the rendered HTML does not expose the application to potential security vulnerabilities (e.g., use a library like `dompurify` to sanitize inputs).

**Technical Notes:**
- Utilize React’s `dangerouslySetInnerHTML` with caution, ensuring that all content is sanitized.
- Add tests to verify that the component correctly renders the desired language content.
- Document the component's updated props and usage examples in the project’s documentation.

**Additional Information:**
- This update should maintain the existing styling and structure of the `FeaturedAnnouncement` component.
- Ensure backward compatibility if the component is already used elsewhere in the project.

**Comment by fcendesu** [comment]
I would like to handle that issue
